spring:
  application.name: notzero-wallet-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:wallet_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: polymath
    password: 1234
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    user: polymath
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org.springdoc: DEBUG
    org.springframework: DEBUG